package com.project.models;
// Generated Nov 4, 2022, 7:41:33 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "warehouse_management")
public class Account implements java.io.Serializable {

	private Integer id;
	
	@Length(min = 5, max = 25)
	@NotEmpty
	private String username;
	
	//@Pattern(regexp = "((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20})")
	@NotEmpty
	private String password;
	
	@NotEmpty
	private String fullName;
	
	@NotEmpty
	@Pattern(regexp = "((?=.*\\d).{10,10})")
	private String phone;
	
	@Email
	@NotEmpty
	private String email;
	private String role;
	
	
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Past
	@NotNull
	private Date dob;
	private String photo;
	private boolean status;
	private Set<InvoiceImport> invoiceImports = new HashSet<InvoiceImport>(0);
	private Set<InvoiceExport> invoiceExports = new HashSet<InvoiceExport>(0);

	public Account() {
	}

	public Account(String username, String password, String fullName, String phone, String email, String role, Date dob,
			String photo, boolean status) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.phone = phone;
		this.email = email;
		this.role = role;
		this.dob = dob;
		this.photo = photo;
		this.status = status;
	}

	public Account(String username, String password, String fullName, String phone, String email, String role, Date dob,
			String photo, boolean status, Set<InvoiceImport> invoiceImports, Set<InvoiceExport> invoiceExports) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.phone = phone;
		this.email = email;
		this.role = role;
		this.dob = dob;
		this.photo = photo;
		this.status = status;
		this.invoiceImports = invoiceImports;
		this.invoiceExports = invoiceExports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "role", nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "photo", nullable = false, length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<InvoiceImport> getInvoiceImports() {
		return this.invoiceImports;
	}

	public void setInvoiceImports(Set<InvoiceImport> invoiceImports) {
		this.invoiceImports = invoiceImports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<InvoiceExport> getInvoiceExports() {
		return this.invoiceExports;
	}

	public void setInvoiceExports(Set<InvoiceExport> invoiceExports) {
		this.invoiceExports = invoiceExports;
	}

}
