package com.project.models;
// Generated Nov 4, 2022, 7:41:33 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Length;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "warehouse_management")
public class Customer implements java.io.Serializable {

	private Integer id;
	
	@NotEmpty
	@Length(min = 5, max = 200)
	private String fullName;
	
	@Pattern(regexp = "((?=.*\\d).{10,10})")
	private String phone;
	
	@NotEmpty
	@Length(min = 5, max = 200)
	private String address;
	
	@NotEmpty
	@Email
	private String email;
	private Set<InvoiceExport> invoiceExports = new HashSet<InvoiceExport>(0);

	public Customer() {
	}

	public Customer(String fullName, String phone, String address, String email) {
		this.fullName = fullName;
		this.phone = phone;
		this.address = address;
		this.email = email;
	}

	public Customer(String fullName, String phone, String address, String email, Set<InvoiceExport> invoiceExports) {
		this.fullName = fullName;
		this.phone = phone;
		this.address = address;
		this.email = email;
		this.invoiceExports = invoiceExports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "full_name", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<InvoiceExport> getInvoiceExports() {
		return this.invoiceExports;
	}

	public void setInvoiceExports(Set<InvoiceExport> invoiceExports) {
		this.invoiceExports = invoiceExports;
	}

}
