package com.project.models;
// Generated Nov 4, 2022, 7:41:33 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoiceImportDetailsId generated by hbm2java
 */
@Embeddable
public class InvoiceImportDetailsId implements java.io.Serializable {

	private int invoiceImportId;
	private int productId;

	public InvoiceImportDetailsId() {
	}

	public InvoiceImportDetailsId(int invoiceImportId, int productId) {
		this.invoiceImportId = invoiceImportId;
		this.productId = productId;
	}

	@Column(name = "invoice_import_id", nullable = false)
	public int getInvoiceImportId() {
		return this.invoiceImportId;
	}

	public void setInvoiceImportId(int invoiceImportId) {
		this.invoiceImportId = invoiceImportId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceImportDetailsId))
			return false;
		InvoiceImportDetailsId castOther = (InvoiceImportDetailsId) other;

		return (this.getInvoiceImportId() == castOther.getInvoiceImportId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvoiceImportId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
