package com.project.models;
// Generated Nov 4, 2022, 7:41:33 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvoiceExportDetails generated by hbm2java
 */
@Entity
@Table(name = "invoice_export_details", catalog = "warehouse_management")
public class InvoiceExportDetails implements java.io.Serializable {

	private InvoiceExportDetailsId id;
	private InvoiceExport invoiceExport;
	private Product product;
	private double price;
	private int quantity;
	private String unit;

	public InvoiceExportDetails() {
	}

	public InvoiceExportDetails(InvoiceExportDetailsId id, InvoiceExport invoiceExport, Product product, double price,
			int quantity, String unit) {
		this.id = id;
		this.invoiceExport = invoiceExport;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
		this.unit = unit;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceExportId", column = @Column(name = "invoice_export_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
	public InvoiceExportDetailsId getId() {
		return this.id;
	}

	public void setId(InvoiceExportDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_export_id", nullable = false, insertable = false, updatable = false)
	public InvoiceExport getInvoiceExport() {
		return this.invoiceExport;
	}

	public void setInvoiceExport(InvoiceExport invoiceExport) {
		this.invoiceExport = invoiceExport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "unit", nullable = false, length = 20)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

}
