package com.project.models;
// Generated Nov 4, 2022, 7:41:33 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoiceExportDetailsId generated by hbm2java
 */
@Embeddable
public class InvoiceExportDetailsId implements java.io.Serializable {

	private int invoiceExportId;
	private int productId;

	public InvoiceExportDetailsId() {
	}

	public InvoiceExportDetailsId(int invoiceExportId, int productId) {
		this.invoiceExportId = invoiceExportId;
		this.productId = productId;
	}

	@Column(name = "invoice_export_id", nullable = false)
	public int getInvoiceExportId() {
		return this.invoiceExportId;
	}

	public void setInvoiceExportId(int invoiceExportId) {
		this.invoiceExportId = invoiceExportId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceExportDetailsId))
			return false;
		InvoiceExportDetailsId castOther = (InvoiceExportDetailsId) other;

		return (this.getInvoiceExportId() == castOther.getInvoiceExportId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvoiceExportId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
