package com.project.models;
// Generated Nov 4, 2022, 7:41:33 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Positive;

import org.hibernate.validator.constraints.Length;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "warehouse_management")
public class Supplier implements java.io.Serializable {

	private Integer id;
	
	@NotEmpty
	@Length(min = 5, max = 200)
	private String name;
	
	@NotEmpty
	@Length(min = 5, max = 200)
	private String address;
	
	@NotEmpty
	@Email
	private String email;
	private String logo;
	
	@NotEmpty
	@Length(min = 5, max = 200)
	private String businessRegistration;
	
	@Pattern(regexp = "((?=.*\\d).{10,10})")
	@Positive
	private String phone;
	private Set<InvoiceImport> invoiceImports = new HashSet<InvoiceImport>(0);

	public Supplier() {
	}

	public Supplier(String name, String address, String email, String logo, String businessRegistration, String phone) {
		this.name = name;
		this.address = address;
		this.email = email;
		this.logo = logo;
		this.businessRegistration = businessRegistration;
		this.phone = phone;
	}

	public Supplier(String name, String address, String email, String logo, String businessRegistration,
			Set<InvoiceImport> invoiceImports) {
		this.name = name;
		this.address = address;
		this.email = email;
		this.logo = logo;
		this.businessRegistration = businessRegistration;
		this.invoiceImports = invoiceImports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "logo", nullable = false, length = 250)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "business_registration", nullable = false, length = 250)
	public String getBusinessRegistration() {
		return this.businessRegistration;
	}

	public void setBusinessRegistration(String businessRegistration) {
		this.businessRegistration = businessRegistration;
	}
	
	@Column(name = "phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<InvoiceImport> getInvoiceImports() {
		return this.invoiceImports;
	}

	public void setInvoiceImports(Set<InvoiceImport> invoiceImports) {
		this.invoiceImports = invoiceImports;
	}

}
